[workspace]
resolver = "2"
members = [
    "crates/qrag-core",
    "crates/qrag-server",
     "crates/qrag-tui",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
result_large_err = "allow"

[workspace.dependencies]
anyhow = "1.0.102"
tokio = { version = "1", features = ["full"] }
rig = "0.37.0"
rig-qdrant = "0.2"
qdrant-client = "1"
tonic = "0.12"
prost = "0.13"
tonic-build = "0.12"
dotenvy = "0.15"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }
futures = "0.3"